### ISSUE TITLE
Getting started page footer overlaps text

### ISSUE THREAD

**Issue by thaJeztah** [docker/docs-base#210]
As reported on twitter:
https://twitter.com/vhmth/status/695392056391303168

> "was user tested to reduce the chance of users having problems." Footer covers copy. https://docs.docker.com/mac/  

Chrome Version 48.0.2564.103 (64-bit)
OSX El Capitan 10.11.12

![caahy_tvaamzrde](https://cloud.githubusercontent.com/assets/1804568/12834575/bad5913c-cba8-11e5-9eb7-5eafe8c1f416.png)

**Comment by thaJeztah** [comment]
Ping @SvenDowideit think that's in this repository; would you be able to look into this?

**Comment by dnephin** [comment]
Note: I believe this is only an issue on that page (which seems to have very different style), not every page.  

I think the issue should be fixed by adjusting the HTML on this page, the css is correct.

I have no idea where this page comes from, but adding `id="docs"` to the main div (current it's just `<div class="row">`) fixes the problem.

**Comment by dnephin** [comment]
Fixed by #211

**Comment by thaJeztah** [comment]
Thanks @dnephin; closing
