### ISSUE TITLE
Left sidebar folds after navigating to subpage

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docs-base#42]
When I click something from the sidebar and the page loads, sidebar state is reset and it goes back to this, which totally makes me lose track about where I am and where I left off.

![image](https://cloud.githubusercontent.com/assets/159209/8245614/9aec9b8c-15e5-11e5-94fb-8bb83a84c49c.png)

**Comment by moxiegirl** [comment]
@ahmetalpbalkan Thank you for the feedback.  The menu was a last minute adjustment due to a time crunch which is to say we definitely need to change the UX.  If you have a link to a site where you like the nav, sling the link here.

I'm not able to repro but I can see that it is confusing.

Check to make sure you aren't just clicking on the "blue bar" which is only a label not a link. Clicking on a blue bar will close and open the menu for sure.

**Comment by ahmetalpbalkan** [comment]
cc: @dmp42

**Comment by moxiegirl** [comment]
@ahmetalpbalkan This is fixed. The menu action is not ideal though because of the jump on redraw.  That issue is being addressed when we upgrade our menu after Dockercon.
