### ISSUE TITLE
No easy way to get to website homepage

### ISSUE THREAD

**Issue by bfirsh** [docker/docs-base#52]
I expect clicking the logo top left to take me to www.docker.com, but it takes me to the home page of the docs.

Perhaps the top item in the left-hand side docs menu could be "Docs Home" or similar, making it clear that is how you get to the home page of the docs. The logo can then link to www.docker.com.

**Comment by moxiegirl** [comment]
@bfirsh I implemented logo as **docs.docker.com** home last night. Give it try reopen if you don't like the action.  We are implementing a common header footer in the next couple of weeks across all the sites --- I'll see if logo=SITE-HOME-BASE across them all.

**Comment by bfirsh** [comment]
I think it makes sense for the logo to go to www.docker.com across all sites, otherwise there's no easy way to get there.

We could add a "Docs Home" link to the documentation menu on the left hand side, then users can easily go to both. Does that make sense?

**Comment by moxiegirl** [comment]
I'll try switching it out to www next push.

![image](https://cloud.githubusercontent.com/assets/1347209/8269482/06b464d8-175f-11e5-8b12-5c0706b2c5ca.png)


Maybe we don't need to add a `Docs Home` to our menu because `Docs` on the main menu takes you to Docs Home?  Though, sounds like you didn't realize it.  I know Nick wants to UX the menu, I'll bring this up to him.

**Comment by bfirsh** [comment]
For users looking to get to docs home, they'll go to the top left, and may not see that link in the top right. If there's a "Docs Home" link at the top of the docs menu on the left-hand side it'll help those users looking to the top-left and make it really clear where the logo goes.

**Comment by moxiegirl** [comment]
I'm closing this in favor of #51 as the new header/footer subsumes this issue
